spring:
  application:
    name: Proxy Server
  profiles:
    active: dev
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-secret: ${app.client-secret}
          client-id: ${app.client-id}
        profile:
          tenant-id: ${app.tenant-id}
        app-id-uri: ${app.uri-id}
        authorization-clients:
          graph:
            scopes:
              - email
              - openid
              - profile
              - User.Read
server:
  port: 8080
  forward-headers-strategy: native
